version: "3.3"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asphere-api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
